import path from 'node:path';

// A reason to defer expensive symbol extraction, never a claim of irrelevance.
export function extractionPolicy(file,text,{parseGenerated=false,parsePath}={}) {
 const reasons=[];
 if(/\.(?:[cm]?[jt]s|[jt]sx)$/.test(file)) {
  if(/\.min\.[cm]?[jt]s$/.test(file))reasons.push('minified-filename');
  if(/(?:@generated|generated by|do not edit)/i.test(text.slice(0,600)))reasons.push('generated-header-candidate');
  if(text.split('\n').some(line=>line.length>20000))reasons.push('very-long-code-line');
 }
 return {deferred:reasons.length>0&&!parseGenerated&&parsePath!==file,reasons};
}

const count=(items,key)=>Object.fromEntries([...items.reduce((m,x)=>m.set(key(x),(m.get(key(x))||0)+1),new Map())].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0])));
export function materialProfile(files) {
 const groups=new Map();for(const f of files){const ps=groups.get(f.oid)||[];ps.push(f.path);groups.set(f.oid,ps);}
 const duplicateGroups=[...groups.values()].filter(ps=>ps.length>1);
 const entryCandidates=files.filter(f=>/(?:^|\/)(?:README(?:\.[^/]+)?|SKILL\.md|AGENTS\.md|CLAUDE\.md|package\.json|pyproject\.toml|Cargo\.toml|go\.mod|__main__\.py)$/i.test(f.path));
 return {extensions:count(files,f=>path.extname(f.path).toLowerCase()||'(none)'),
  topDirectories:count(files,f=>f.path.includes('/')?f.path.split('/')[0]:'(root)'),kinds:count(files,f=>f.kind),
  parsers:count(files,f=>f.parser||'unreadable'),unreadableReasons:count(files.filter(f=>!f.readable),f=>f.scan||'unknown'),
  deferredFiles:files.filter(f=>f.parser==='deferred-generated').length,
  duplicateGroups:duplicateGroups.length,duplicatePaths:duplicateGroups.reduce((s,g)=>s+g.length-1,0),
  entryCandidates:{total:entryCandidates.length,paths:entryCandidates.slice(0,30).map(f=>f.path),limit:30},
  limits:['Entry candidates are filename hints, not discovered product responsibilities.',
   'Generated/minified candidates stay readable; override deferral for a selected path or all candidates.',
   'Python AST uses the selected interpreter grammar; syntax diagnostics mean no symbols for that file.',
   'Duplicate paths share bytes, not necessarily meaning or runtime role.']};
}
